name: Build SunamoUnderscore

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoUnderscore
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoUnderscore/SunamoUnderscore.csproj

    - name: Build
      run: dotnet build SunamoUnderscore/SunamoUnderscore.csproj --configuration Release --no-restore

  test:
    name: Test SunamoUnderscore.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoUnderscore.Tests/SunamoUnderscore.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoUnderscore.Tests/SunamoUnderscore.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoUnderscore.Tests/SunamoUnderscore.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
